### ISSUE TITLE
Resizing DDS cube faces

### ISSUE THREAD

**Issue by Niedzwiedzw** [ScanMountGoat/image_dds#23]
Hey, I can't say I know too much about dds, but still I'm trying to port certain functionality from a C# application - this Recompress function:

https://github.com/wabbajack-tools/wabbajack/blob/df84ae1ecb729cd964cbbd452fc54a8605943dac/Wabbajack.Hashing.PHash/CrossPlatformImageLoader.cs#L73

I would be super grateful for taking a look and advising me on how to tackle that

**Comment by ScanMountGoat** [comment]
It looks like the code is just decoding, resizing, and encoding again. DDS can use 4x4 pixel block compression, so you typically want to decode first before performing any operations. Cube maps often use HDR formats, so I would use the floating point surface type to not lose values outside the 0.0 to 1.0 range when decoding and encoding. I've outlined the basic steps below. 

```rust
// load dds from file
let surface = image_dds::Surface::from_dds(&dds)?;
let decoded = surface.decode_rgbaf32()?;
// create new_surface image_dds::SurfaceRgba32Float with resized data from decoded
let encoded = new_surface.encode(format, quality, mipmaps)?;
let new_dds = encoded.to_dds()?;
// save dds
```

The ergonomics of actually getting the image data for each layer and mip and recombining them could definitely be better. Let me know if you run into any issues, and I can look at adding more methods to the surface types. The expected data layout for how to pack layers and mips is in the documentation for the surface types. 
https://docs.rs/image_dds/latest/image_dds/struct.SurfaceRgba32Float.html

**Comment by Niedzwiedzw** [comment]
hmm do I need to do anything specific about cube faces? cause this seems to be the main focus of the code in that function, the C# `DdsFile` has `.faces()` method for that

**Comment by ScanMountGoat** [comment]
image_dds stores the image data in a combined buffer for performance. You'll need to get each face for each mip with `decoded.get(...)`, resize them, and then add to the new surface with layers in the outer loop and mip maps in the inner loop. The image crate has a resize function you can use. 

This would be a lot easier if I had a version of the get function that returns an image with the appropriate dimensions. I may even look into adding a resize_dds example.

**Comment by Niedzwiedzw** [comment]
all right I think i'll handle it from here :D in case you're curious I'm working on this https://github.com/Niedzwiedzw/hoolamike (linux-compatible wabbajack modlist installer) and this is the final piece :D

**Comment by Niedzwiedzw** [comment]
hmm so how do I get faces exactly? is face the same as layer?

**Comment by ScanMountGoat** [comment]
Yes. Cube maps have six layers.

**Comment by Niedzwiedzw** [comment]
hmm yeah about resizing,  the &[f32] I'm getting from .get(), do I convert it into `DynamicImage` from `image` somehow? I'll be sure to contribute the full example once I'm done with it with it btw xP

**Comment by ScanMountGoat** [comment]
https://docs.rs/image/latest/image/type.Rgba32FImage.html

**Comment by Niedzwiedzw** [comment]
all right so here's what I came up with:
https://github.com/Niedzwiedzw/hoolamike/blob/feature/dds-recompression/crates/hoolamike/src/install_modlist/directives/transformed_texture/dds_recompression.rs

of course I'm gonna double check with the original to see if they're not doing anything extra but could you please take a look if this looks sane?

EDIT: pushed some extra stuff since posting

**Comment by ScanMountGoat** [comment]
The high level approach looks ok.

**Comment by Niedzwiedzw** [comment]
to be more specific I wonder about the creation of new surface, I'm just merging all the parts in order (by_layer -> by_depth -> by_mipmap) into a single Vec<f32>... the order probably matters here right :D

**Comment by ScanMountGoat** [comment]
Combining data is correct. You can test the ordering by exporting an image for a particular mip level using the dds2img example. It should be pretty obvious if the ordering is incorrect.

**Comment by Niedzwiedzw** [comment]
all right it compiles and something happens, I'll manually go through the outputs tomorrow like you suggested. thank you very much for your help and for this library, I'll be sure to give you a shoutout in the readme once this works
